name: plir-github-actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # workflow_dispatch:  

jobs:
  build-plir:
    runs-on: ubuntu-latest
    steps:
    # - name: 'Cloning plir-dockerised-set-up'
    # run: |
    #   snip
    #   git clone https://github.com/openmrs/openmrs-plir-dockerized-setup.git 
    - name: Checkout in plir dockerised setup
      uses: actions/checkout@main
      with:
        repository: openmrs/openmrs-plir-dockerized-setup.git
        # path: openmrs-plir-dockerized-setup.git
    - name:  run plir setup 
      run:   |
              chmod +x ./run.sh        

  build-hie:
    needs: build-plir
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    - name: Set up behave
      run: pip install behave
    steps:
    # - name: 'Cloning hie automation framework'
    # run: |
    #   snip
    #   git clone https://github.com/openmrs/hie-automation-tests.git  
    - name: Checkout in hie automation tests
      uses: actions/checkout@master
      with:
        repository: openmrs/hie-automation-tests.git
        # path: hie-automation-tests.git
    - name:  run automation tests
      run: behave --no-logcapture --include ./features/PLIR                   
    